name: deployment pankuru back
on: [push]
jobs:
  create-folder:
    name: create folder
    runs-on: ubuntu-latest
    steps:
      - name: execute commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            mkdir /opt/applications/pankuru/pankuru-back
            ls -al /opt/applications/pankuru
